title: mkouhia
author: Mikko Kouhia
email: mkouhia@iki.fi
description: >
  A collection of technical notes

theme: minima

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  
github_username: mkouhia
linkedin_username: mkouhia
rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
